name: Build and deploy Chrona UI

on:
#  push:
#    tags: [ "*" ]

  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Get BACKEND_API_URL_PROD from App Settings
        id: get-backend-url
        run: |
          VALUE=$(az keyvault secret show --vault-name ${{ secrets.KEY_VAULT_NAME }} --name "BASE-URL" --query "value" -o tsv)
          echo "backend_url=$VALUE" >> $GITHUB_OUTPUT

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.REGISTRY_NAME }}/chrona-frontend:latest
          file: ./Dockerfile
          build-args: |
            BACKEND_URL=${{ steps.get-backend-url.outputs.backend_url }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: production

    steps:
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      - name: Inject BACKEND_API_URL to App
#        run: |
#          az webapp config appsettings set \
#            --name "${{ secrets.AZURE_WEBAPP_NAME }}" \
#            --resource-group "${{ secrets.AZURE_RG }}" \
#            --settings BACKEND_APP_URL=${{ steps.get-backend-url.outputs.backend_url }}

      - name: Set Container Settings + Enable CD
        run: |
          az webapp config container set \
            --name "${{ secrets.AZURE_WEBAPP_NAME }}" \
            --resource-group "${{ secrets.AZURE_RG }}" \
            --docker-custom-image-name "${{ secrets.REGISTRY_NAME }}/chrona-frontend:latest" \
            --docker-registry-server-url "https://${{ secrets.REGISTRY_NAME }}" \
            --docker-registry-server-user "${{ secrets.ACR_USERNAME }}" \
            --docker-registry-server-password "${{ secrets.ACR_PASSWORD }}"

          az webapp deployment container config \
            --enable-cd true \
            --name "${{ secrets.AZURE_WEBAPP_NAME }}" \
            --resource-group "${{ secrets.AZURE_RG }}"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.REGISTRY_NAME }}/chrona-frontend:latest
