# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chrona-frontend(pr-1)

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chrona.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6fbd37c76e3d49d394e6f15fced7e343 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6030b0b64b7e461cb7e921f645011ea6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chrona.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6fbd37c76e3d49d394e6f15fced7e343 }}/chrona-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'pr-1'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chrona-frontend'
        slot-name: 'pr-1'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8bc8661fbbe64ea6916bb1d31d062aad }}
        images: 'chrona.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6fbd37c76e3d49d394e6f15fced7e343 }}/chrona-frontend:${{ github.sha }}'