name: PR Cleanup (Isolated App Teardown)

on:
  pull_request:
    types: [closed]
    branches: [master]

permissions:
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Azure Login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Cleanup Variables
        id: vars
        run: |
          echo "APP=pr-${{ github.event.number }}-chrona-frontend" >> $GITHUB_ENV
          echo "PLAN=pr-${{ github.event.number }}-chrona-plan" >> $GITHUB_ENV
          echo "APP_URL=https://pr-${{ github.event.number }}-chrona-frontend.azurewebsites.net" >> $GITHUB_ENV

      - name: Cleanup App Service and Plan
        run: |
          echo "🧹 Checking for app: $APP"

          if [ "$PLAN" != "chronaplan-pr-1" ]; then
            echo "🧹 Deleting App and App Service Plan: $PLAN"
            az webapp delete --name "$APP" --resource-group "${{ secrets.AZURE_RG }}"
            az appservice plan delete --name "$PLAN" --resource-group "${{ secrets.AZURE_RG }}" --yes
            echo "✅ App and Service Plan deleted."
          else
            echo "⚠️ Skipping Service Plan Deletion for $PLAN"
            az webapp delete --name "$APP" --resource-group "${{ secrets.AZURE_RG }}"
            echo "✅ App deleted. Service Plan $PLAN retained."
          fi

      - name: Remove Preview URL from Vault Secrets
        run: |
          VAULT_NAME=${{ secrets.KEY_VAULT_NAME }}

          echo "Fetching current ALLOWED_HOSTS and CORS_ALLOWED_ORIGINS..."
          EXISTING_ALLOWED=$(az keyvault secret show --vault-name "$VAULT_NAME" --name "ALLOWED-HOSTS" --query "value" -o tsv)
          EXISTING_CORS=$(az keyvault secret show --vault-name "$VAULT_NAME" --name "CORS-ALLOWED-ORIGINS" --query "value" -o tsv)

          echo "Removing from ALLOWED-HOSTS..."
          UPDATED_ALLOWED=$(echo "$EXISTING_ALLOWED" | sed "s#${APP_URL},*##g" | sed 's#,,#,#g' | sed 's#^,\|,$##g')
          az keyvault secret set --vault-name "$VAULT_NAME" --name "ALLOWED-HOSTS" --value "$UPDATED_ALLOWED"

          echo "Removing from CORS-ALLOWED-ORIGINS..."
          UPDATED_CORS=$(echo "$EXISTING_CORS" | sed "s#${APP_URL},*##g" | sed 's#,,#,#g' | sed 's#^,\|,$##g')
          az keyvault secret set --vault-name "$VAULT_NAME" --name "CORS-ALLOWED-ORIGINS" --value "$UPDATED_CORS"

      - name: Update backend Container App env vars
        run: |
          BACKEND_APP=${{ secrets.BACKEND_CONTAINER_APP_NAME }}
          RG=${{ secrets.AZURE_RG }}
          VAULT_NAME=${{ secrets.KEY_VAULT_NAME }}

          NEW_ALLOWED=$(az keyvault secret show --vault-name "$VAULT_NAME" --name "ALLOWED-HOSTS" --query "value" -o tsv)
          NEW_CORS=$(az keyvault secret show --vault-name "$VAULT_NAME" --name "CORS-ALLOWED-ORIGINS" --query "value" -o tsv)

          az containerapp secret set --name "$BACKEND_APP" --resource-group "$RG" \
            --secrets allowed-hosts="$NEW_ALLOWED" \
                      cors-allowed-origins="$NEW_CORS"
