name: Build and deploy Time App

on:
  push:
    branches: [ "develop", "staging"]
    tags: [ "*" ]

  workflow_dispatch:

permissions:
  contents: read

jobs:

  prepare:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.set-env.outputs.ENVIRONMENT }}
    steps:
      - name: Determine Environment
        id: set-env
        run: |
          REF_TYPE="${GITHUB_REF#refs/*/}"
          REF_NAME="${GITHUB_REF##*/}"

          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            if [ "$REF_NAME" = "develop" ]; then
              echo "ENVIRONMENT=develop" >> $GITHUB_OUTPUT
            elif [ "$REF_NAME" = "staging" ]; then
              echo "ENVIRONMENT=staging" >> $GITHUB_OUTPUT
            elif [ "$REF_NAME" = "master" ]; then
              echo "ENVIRONMENT=production" >> $GITHUB_OUTPUT
            else
              echo "ENVIRONMENT=unknown" >> $GITHUB_OUTPUT
            fi
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Get Env Variables
        run: |
          echo "Environment: ${{ steps.set-env.outputs.ENVIRONMENT }}"

  build:
    runs-on: ubuntu-latest
    needs: prepare
    environment:
      name: ${{ needs.prepare.outputs.ENVIRONMENT }}

    steps:

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.REPO }}-${{ needs.prepare.outputs.ENVIRONMENT }}-frontend:latest
          file: ./Dockerfile

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [prepare, build]
    environment:
      name: ${{ needs.prepare.outputs.ENVIRONMENT }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.APP_NAME }}
          images: ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.REPO }}-${{ needs.prepare.outputs.ENVIRONMENT }}:latest
